// Generated by CoffeeScript 1.7.1
(function() {
  var b;

  b = 0;

  $('#cat-button').click(function(event) {
    var test;
    alert("test");
    test = $('#cat-button').attr('src');
    return $('#h1').html(test);
  });

  $('.btn').click(function(event) {
    $("#h1").append(" boo ");
    $('#h1').html((b = b + 1));
    return $(this).attr('src', "http://macosx.com/forums/customavatars/avatar4065_1.gif");
  });

}).call(this);
